### ISSUE TITLE
The issue of calculated property values mismatch upon reordering the components 

### ISSUE THREAD

**Issue by msuresh20** [usnistgov/REFPROP-issues#88]
### Description
The issue of calculated property values mismatch upon reordering the components 

[Description of the issue]
Different Component Orders giving different property results 

Test Case 1:  1_1BD_1Buty_1PENT_22MB.rfp vs 1_1BD_1Buty_1PENT_22MB_diff_ordered.rfp
Component Orders: 1,3-Butadiene/1-Butyne/1-Pentene/2,2-Dimethylbutane: Specified state points (0.25/0.25/0.25/0.25) VS  1-Butyne/2,2-Dimethylbutane/1-Pentene/1,3-Butadiene: Specified state points (0.25/0.25/0.25/0.25)
Observation: Different Component Orders different results 

Test case 2:  2_23MB_3MP_ACETY_CL.rfp vs 2_23MB_3MP_ACETY_CL_diff_order.rfp
Component orders: 2,3-Dimethylbutane/3-Methylpentane/Acetylene/Chlorine: Specified state points (0.25/0.25/0.25/0.25) VS 3-Methylpentane/Chlorine/2,3-Dimethylbutane/Acetylene: Specified state points (0.25/0.25/0.25/0.25)
Observations: Different Component orders giving different values (same as test case 1)

### Steps to Reproduce

1. [First Step]
 Under Define new mixture, select these components--> 1,3-Butadiene/1-Butyne/1-Pentene/2,2-Dimethylbutane
2. [Second Step]
Used Default Equation of state i.e., NIST23 method 
Specifiy molar composition (0.25/0.25/0.25/0.25)
3. Configure properties --> Density, Enthalpy, Entropy, Internal Energy, Cp properties.

Under Specified state points --> Select Temperature as 300 K, Pressure as 300 Kpa 
**Expected behavior:** [What you expect to happen]
The property values should match what ever order of components was selected. 
**Actual behavior:** [What actually happens]
Different Component Orders giving different results 
### Versions

**REFPROP Version:** 10.0.0.2
**Operating System and Version:** [Windows 10]  
**Access Method:** [C++)]  

### Additional Information

Please refer to the attached zip file "1_Mismatches.zip" where in attached the REFPROP input, output result files. 
[1_Mismatches.zip](https://github.com/usnistgov/REFPROP-issues/files/2781459/1_Mismatches.zip)

**Comment by EricLemmon** [comment]
Thanks for reporting this bug!  This is quite a serious issue that no one else has caught and I appreciate that you found it and reported it.  The bug has been fixed now and I will send you a new DLL for testing.  If you find that the new DLL works without problems, please let us know (here) and then close the issue.  Of course, if you also find it is not fixed, let us know!!!

**Comment by jpk-jpk** [comment]
Hello  @EricLemmon, 

Can you please reopen the issue? 
The issue mentioned above is still reproducible.

This is especially reproducible with the new components introduced in the Refprop 10.0 

The same procedure was followed with the latest dll. 

Version Information
REFPROP Version: **10.0.0.85**
Operating System and Version: **[Windows 10]**
Access Method: Standalone **Refprop Application**

Components used are 
- 1-Butyne
- 2,2-Dimethylbutane
- 1,3-Butadiene
- 1-Pentene

**Files** 
[Newcomp_issue.zip](https://github.com/usnistgov/REFPROP-issues/files/5416888/Newcomp_issue.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/30909049/96738055-f2f77000-13db-11eb-9c3e-22ca4c222074.png)

**Comment by EricLemmon** [comment]
I am not quite sure why I thought this had been fixed a year ago, upon re-examining things, I found the problem still to be there.  I was able to track down the reason for this, and found that it only occurs when two fluids have the same molar mass.  For Version 10.0, Ian Bell developed a predictive method to estimate the interaction parameters for binary combinations of fluids when both constituents are hydrocarbons.  The method is based on the molar masses of the two fluids, with the molar mass of the lighter component used as the input to the predictive method.  When the molar masses are the same, then, obviously, either one can be used as the input!  However, calculated properties will not be the same depending on which fluid is chosen due to complications that I will not discuss here.

I set up a small program to test every possible binary mixture with the 150 or so fluid files that we have available.  Of the 11,500 possible binary pairs, there were only nine that were affected by this issue, these being:

1,3-butadiene + 1-butyne
1-pentene + cyclopentane
2,2-dimethylbutane + 2,3-dimethylbutane
2,2-dimethylbutane + 3-methylpentane
2,2-dimethylbutane + hexane
2,3-dimethylbutane + 3-methylpentane
2,3-dimethylbutane + hexane
3-methylpentane + hexane
propadiene + propyne

All of the other pairs that have the same molar masses use different methods to obtain the interaction parameters, and these other methods do not use the molar mass as input.  The most common of these methods is the use of the interaction parameters for an alternative but similar fluid.  Most of the fluids here could use propane, butane, pentane, or hexane (i.e., propane for propadiene, hexane for 2,2-dimethylbutane, etc.) as the alternative fluid.  The addition of alternative fluids to the fluid files was done for all fluids in the 10.0 release, except for six of the fluids listed above that were added shortly before the release date.

I will update the fluid files for the six fluids and make them available to you.  Ian and I will need to discuss how to update the predictive method for future situations where this issue is relevant.

**Comment by ianhbell** [comment]
This is the reference that the estimation scheme for normal alkane + normal alkane comes from: https://pubs.acs.org/doi/10.1021/acs.jced.6b00257

**Comment by brentcfisher** [comment]
We've noticed the problem originally described in this issue as well - although not with the mixtures mentioned above by @EricLemmon.  It seems when we have a large number of components, re-ordering them results in different property values.

For instance, using the following composition:

> Carbon dioxide	0.0
> Decane	0.0
> Heptane	0.0
> Hexane	0.0
> Isobutane	0.0
> Isopentane	0.0
> Methane	0.0
> Nitrogen	0.0
> Nonane	0.0
> Octane	0.0
> Pentane	0.0
> Propane	0.4
> Butane	0.0
> Carbon monoxide	0.0
> Ethane	0.6

Yields the following properties:
![image](https://user-images.githubusercontent.com/28545447/134248687-0558bb48-4b09-493f-bb3d-3b4adaceae2f.png)

Using the same composition in a different order, however:

> Carbon monoxide	0.0
> Carbon dioxide	0.0
> Decane	0.0
> Ethane	0.6
> Heptane	0.0
> Hexane	0.0
> Isobutane	0.0
> Isopentane	0.0
> Methane	0.0
> Nitrogen	0.0
> Nonane	0.0
> Octane	0.0
> Pentane	0.0
> Propane	0.4
> Butane	0.0

Is giving us different property values:
![image](https://user-images.githubusercontent.com/28545447/134248821-b2db0c53-e7da-4d31-b9b6-7fe4766cc0ac.png)

We could likely mitigate the discrepancies by always ordering components the same way but that would require knowing what order yields the most correct property values. 

**Versions:**
**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10

**Comment by EricLemmon** [comment]
I just tried your mixture with the current beta that I have and all worked well out to 12 or more digits.  Send Ian.Bell@nist.gov an email and he'll direct you to the latest version.
